### ISSUE TITLE
Error in Sensirion.cpp

### ISSUE THREAD

**Issue by rlieberman** [openhomeautomation/wireless-gardening-arduino#2]
Hi,

I just tried to run the Arduino test sketch and I'm getting the following error in the Arduino console. 

Am I using an outdated version of the library? Any other ideas as to why I might be getting this issue?

Arduino: 1.6.0 (Mac OS X), Board: "Arduino Uno"

Build options changed, rebuilding all
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:27:10: error: #include expects "FILENAME" or <FILENAME>
 #include "Arduino.h
          ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp: In constructor 'Sensirion::Sensirion(uint8_t, uint8_t)':
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:84:22: error: 'OUTPUT' was not declared in this scope
   pinMode(_pinClock, OUTPUT);
                      ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:84:28: error: 'pinMode' was not declared in this scope
   pinMode(_pinClock, OUTPUT);
                            ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp: In member function 'uint8_t Sensirion::meas(uint8_t, uint16_t*, bool)':
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:133:30: error: 'digitalRead' was not declared in this scope
   while (digitalRead(_pinData)) {
                              ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:137:12: error: 'delay' was not declared in this scope
     delay(3);
            ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp: In member function 'uint8_t Sensirion::measRdy()':
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:149:27: error: 'digitalRead' was not declared in this scope
   if (digitalRead(_pinData) != 0)   // Measurement ready yet?
                           ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp: In member function 'uint8_t Sensirion::putByte(uint8_t)':
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:237:21: error: 'OUTPUT' was not declared in this scope
   pinMode(_pinData, OUTPUT);        // Set data line to output mode
                     ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:237:27: error: 'pinMode' was not declared in this scope
   pinMode(_pinData, OUTPUT);        // Set data line to output mode
                           ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:240:40: error: 'digitalWrite' was not declared in this scope
     digitalWrite(_pinData, value & mask);
                                        ^
In file included from /Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:29:0:
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.h:29:40: error: 'delayMicroseconds' was not declared in this scope
 #define PULSE_SHORT delayMicroseconds(1)
                                        ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:241:5: note: in expansion of macro 'PULSE_SHORT'
     PULSE_SHORT;
     ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:242:29: error: 'HIGH' was not declared in this scope
     digitalWrite(_pinClock, HIGH);  // Generate clock pulse
                             ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:244:29: error: 'LOW' was not declared in this scope
     digitalWrite(_pinClock, LOW);
                             ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:248:21: error: 'INPUT' was not declared in this scope
   pinMode(_pinData, INPUT);         // Return data line to input mode
                     ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:250:33: error: 'digitalWrite' was not declared in this scope
   digitalWrite(_pinData, DATA_PU);  // Restore internal pullup state
                                 ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:252:27: error: 'HIGH' was not declared in this scope
   digitalWrite(_pinClock, HIGH);    // Clock #9 for ACK
                           ^
In file included from /Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:29:0:
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.h:28:40: error: 'delayMicroseconds' was not declared in this scope
 #define PULSE_LONG  delayMicroseconds(3)
                                        ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:253:3: note: in expansion of macro 'PULSE_LONG'
   PULSE_LONG;
   ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:254:27: error: 'digitalRead' was not declared in this scope
   if (digitalRead(_pinData))        // Verify ACK ('0') received from sensor
                           ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:257:27: error: 'LOW' was not declared in this scope
   digitalWrite(_pinClock, LOW);     // Finish with clock in low state
                           ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp: In member function 'uint8_t Sensirion::getByte(bool)':
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:267:29: error: 'HIGH' was not declared in this scope
     digitalWrite(_pinClock, HIGH);  // Generate clock pulse
                             ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:267:33: error: 'digitalWrite' was not declared in this scope
     digitalWrite(_pinClock, HIGH);  // Generate clock pulse
                                 ^
In file included from /Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:29:0:
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.h:29:40: error: 'delayMicroseconds' was not declared in this scope
 #define PULSE_SHORT delayMicroseconds(1)
                                        ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:268:5: note: in expansion of macro 'PULSE_SHORT'
     PULSE_SHORT;
     ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:269:35: error: 'digitalRead' was not declared in this scope
     result |= digitalRead(_pinData);  // Merge next bit into LSB position
                                   ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:270:29: error: 'LOW' was not declared in this scope
     digitalWrite(_pinClock, LOW);
                             ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:273:21: error: 'OUTPUT' was not declared in this scope
   pinMode(_pinData, OUTPUT);
                     ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:273:27: error: 'pinMode' was not declared in this scope
   pinMode(_pinData, OUTPUT);
                           ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:274:30: error: 'digitalWrite' was not declared in this scope
   digitalWrite(_pinData, !ack);     // Assert ACK ('0') if ack == 1
                              ^
In file included from /Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:29:0:
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.h:29:40: error: 'delayMicroseconds' was not declared in this scope
 #define PULSE_SHORT delayMicroseconds(1)
                                        ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:275:3: note: in expansion of macro 'PULSE_SHORT'
   PULSE_SHORT;
   ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:276:27: error: 'HIGH' was not declared in this scope
   digitalWrite(_pinClock, HIGH);    // Clock #9 for ACK / noACK
                           ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:278:27: error: 'LOW' was not declared in this scope
   digitalWrite(_pinClock, LOW);     // Finish with clock in low state
                           ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:280:21: error: 'INPUT' was not declared in this scope
   pinMode(_pinData, INPUT);         // Return data line to input mode
                     ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp: In member function 'void Sensirion::startTransmission()':
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:300:26: error: 'HIGH' was not declared in this scope
   digitalWrite(_pinData, HIGH);  // Set data register high before turning on
                          ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:300:30: error: 'digitalWrite' was not declared in this scope
   digitalWrite(_pinData, HIGH);  // Set data register high before turning on
                              ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:301:21: error: 'OUTPUT' was not declared in this scope
   pinMode(_pinData, OUTPUT);     // output driver (avoid possible low pulse)
                     ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:301:27: error: 'pinMode' was not declared in this scope
   pinMode(_pinData, OUTPUT);     // output driver (avoid possible low pulse)
                           ^
In file included from /Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:29:0:
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.h:29:40: error: 'delayMicroseconds' was not declared in this scope
 #define PULSE_SHORT delayMicroseconds(1)
                                        ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:302:3: note: in expansion of macro 'PULSE_SHORT'
   PULSE_SHORT;
   ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:305:26: error: 'LOW' was not declared in this scope
   digitalWrite(_pinData, LOW);
                          ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp: In member function 'void Sensirion::resetConnection()':
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:327:26: error: 'HIGH' was not declared in this scope
   digitalWrite(_pinData, HIGH);  // Set data register high before turning on
                          ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:327:30: error: 'digitalWrite' was not declared in this scope
   digitalWrite(_pinData, HIGH);  // Set data register high before turning on
                              ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:328:21: error: 'OUTPUT' was not declared in this scope
   pinMode(_pinData, OUTPUT);     // output driver (avoid possible low pulse)
                     ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:328:27: error: 'pinMode' was not declared in this scope
   pinMode(_pinData, OUTPUT);     // output driver (avoid possible low pulse)
                           ^
In file included from /Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:29:0:
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.h:28:40: error: 'delayMicroseconds' was not declared in this scope
 #define PULSE_LONG  delayMicroseconds(3)
                                        ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:329:3: note: in expansion of macro 'PULSE_LONG'
   PULSE_LONG;
   ^
/Users/rebeccalieberman/Documents/Arduino/libraries/Sensirion/Sensirion.cpp:333:29: error: 'LOW' was not declared in this scope
     digitalWrite(_pinClock, LOW);
                             ^
Error compiling.

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

**Comment by openhomeautomation** [comment]
Hello! This looks to me like a problem with the Sensirion library indeed. I just tested it, it compiles fine with Arduino 1.6.1

**Comment by Mailbox11-Rep** [comment]
I had this issue. 

Edit your Sensirion.cpp to be the following:

<--- Start: Code --->
extern "C" {
  // AVR LibC Includes
  #include <stddef.h>
  #include <stdint.h>
  #include <math.h>

  // Wiring Core Includes
  // #include "WConstants.h"
}

#include "Sensirion.h"
#include "Arduino.h"

<--- End: Code --->
